services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: dinner
      POSTGRES_PASSWORD: dinner
      POSTGRES_USER: dinner
    ports:
      - 5432:5432

  backend:
    build: backend
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://dinner:dinner@db/dinner
    ports:
      - 9000:9000
    depends_on:
      - redis
      - db
